document.writeln("<script type=\'text/javascript\'>");
document.writeln("	var initPhotoSwipeFromDOM = function(gallerySelector) {");
document.writeln("");
document.writeln("    // ��������DOMԪ�ػõ�Ƭ���ݣ�URL�����⣬��С...��");
document.writeln("    // (children of gallerySelector)");
document.writeln("    var parseThumbnailElements = function(el) {");
document.writeln("        var thumbElements = el.childNodes,");
document.writeln("            numNodes = thumbElements.length,");
document.writeln("            items = [],");
document.writeln("            figureEl,");
document.writeln("            linkEl,");
document.writeln("            size,");
document.writeln("            item,");
document.writeln("			divEl;");
document.writeln("");
document.writeln("        for(var i = 0; i < numNodes; i++) {");
document.writeln("");
document.writeln("            figureEl = thumbElements[i]; // <figure> element");
document.writeln("");
document.writeln("            // ������Ԫ�ؽڵ�");
document.writeln("            if(figureEl.nodeType !== 1) {");
document.writeln("                continue;");
document.writeln("            }");
document.writeln("			divEl = figureEl.children[0];");
document.writeln("            linkEl = divEl.children[0]; // <a> element");
document.writeln("			");
document.writeln("            size = linkEl.getAttribute(\'data-size\').split(\'x\');");
document.writeln("");
document.writeln("            // �����õ�Ƭ����");
document.writeln("            item = {");
document.writeln("                src: linkEl.getAttribute(\'href\'),");
document.writeln("                w: parseInt(size[0], 10),");
document.writeln("                h: parseInt(size[1], 10)");
document.writeln("            };");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            if(figureEl.children.length > 1) {");
document.writeln("                // <figcaption> content");
document.writeln("                item.title = figureEl.children[1].innerHTML; ");
document.writeln("            }");
document.writeln("");
document.writeln("            if(linkEl.children.length > 0) {");
document.writeln("                // <img> ����ͼ�ڵ�, ��������ͼ��ַ");
document.writeln("                item.msrc = linkEl.children[0].getAttribute(\'src\');");
document.writeln("            } ");
document.writeln("");
document.writeln("            item.el = figureEl; // ��������Ԫ�� for getThumbBoundsFn");
document.writeln("            items.push(item);");
document.writeln("        }");
document.writeln("");
document.writeln("        return items;");
document.writeln("    };");
document.writeln("");
document.writeln("    // ��������ĸ��ڵ�");
document.writeln("    var closest = function closest(el, fn) {");
document.writeln("        return el && ( fn(el) ? el : closest(el.parentNode, fn) );");
document.writeln("    };");
document.writeln("");
document.writeln("    // ���û��������ͼ����");
document.writeln("    var onThumbnailsClick = function(e) {");
document.writeln("        e = e || window.event;");
document.writeln("        e.preventDefault ? e.preventDefault() : e.returnValue = false;");
document.writeln("");
document.writeln("        var eTarget = e.target || e.srcElement;");
document.writeln("");
document.writeln("        // find root element of slide");
document.writeln("        var clickedListItem = closest(eTarget, function(el) {");
document.writeln("            return (el.tagName && el.tagName.toUpperCase() === \'FIGURE\');");
document.writeln("        });");
document.writeln("");
document.writeln("        if(!clickedListItem) {");
document.writeln("            return;");
document.writeln("        }");
document.writeln("");
document.writeln("        // find index of clicked item by looping through all child nodes");
document.writeln("        // alternatively, you may define index via data- attribute");
document.writeln("        var clickedGallery = clickedListItem.parentNode,");
document.writeln("            childNodes = clickedListItem.parentNode.childNodes,");
document.writeln("            numChildNodes = childNodes.length,");
document.writeln("            nodeIndex = 0,");
document.writeln("            index;");
document.writeln("");
document.writeln("        for (var i = 0; i < numChildNodes; i++) {");
document.writeln("            if(childNodes[i].nodeType !== 1) { ");
document.writeln("                continue; ");
document.writeln("            }");
document.writeln("");
document.writeln("            if(childNodes[i] === clickedListItem) {");
document.writeln("                index = nodeIndex;");
document.writeln("                break;");
document.writeln("            }");
document.writeln("            nodeIndex++;");
document.writeln("        }");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        if(index >= 0) {");
document.writeln("            // open PhotoSwipe if valid index found");
document.writeln("            openPhotoSwipe( index, clickedGallery );");
document.writeln("        }");
document.writeln("        return false;");
document.writeln("    };");
document.writeln("");
document.writeln("    // parse picture index and gallery index from URL (#&pid=1&gid=2)");
document.writeln("    var photoswipeParseHash = function() {");
document.writeln("        var hash = window.location.hash.substring(1),");
document.writeln("        params = {};");
document.writeln("");
document.writeln("        if(hash.length < 5) {");
document.writeln("            return params;");
document.writeln("        }");
document.writeln("");
document.writeln("        var vars = hash.split(\'&\');");
document.writeln("        for (var i = 0; i < vars.length; i++) {");
document.writeln("            if(!vars[i]) {");
document.writeln("                continue;");
document.writeln("            }");
document.writeln("            var pair = vars[i].split(\'=\');  ");
document.writeln("            if(pair.length < 2) {");
document.writeln("                continue;");
document.writeln("            }           ");
document.writeln("            params[pair[0]] = pair[1];");
document.writeln("        }");
document.writeln("");
document.writeln("        if(params.gid) {");
document.writeln("            params.gid = parseInt(params.gid, 10);");
document.writeln("        }");
document.writeln("");
document.writeln("        return params;");
document.writeln("    };");
document.writeln("");
document.writeln("    var openPhotoSwipe = function(index, galleryElement, disableAnimation, fromURL) {");
document.writeln("        var pswpElement = document.querySelectorAll(\'.pswp\')[0],");
document.writeln("            gallery,");
document.writeln("            options,");
document.writeln("            items;");
document.writeln("");
document.writeln("        items = parseThumbnailElements(galleryElement);");
document.writeln("");
document.writeln("        // ������Զ������");
document.writeln("        options = {");
document.writeln("          barsSize: { ");
document.writeln("            top: 100,");
document.writeln("            bottom: 100");
document.writeln("          }, ");
document.writeln("		   fullscreenEl : false,");
document.writeln("			shareButtons: [");
document.writeln("			{id:\'wechat\', label:\'����΢��\', url:\'#\'},");
document.writeln("			{id:\'weibo\', label:\'����΢��\', url:\'#\'},");
document.writeln("			{id:\'download\', label:\'����ͼƬ\', url:\'{{raw_image_url}}\', download:true}");
document.writeln("			],");
document.writeln("");
document.writeln("            // define gallery index (for URL)");
document.writeln("            galleryUID: galleryElement.getAttribute(\'data-pswp-uid\'),");
document.writeln("");
document.writeln("            getThumbBoundsFn: function(index) {");
document.writeln("                // See Options -> getThumbBoundsFn section of documentation for more info");
document.writeln("                var thumbnail = items[index].el.getElementsByTagName(\'img\')[0], // find thumbnail");
document.writeln("                    pageYScroll = window.pageYOffset || document.documentElement.scrollTop,");
document.writeln("                    rect = thumbnail.getBoundingClientRect(); ");
document.writeln("");
document.writeln("                return {x:rect.left, y:rect.top + pageYScroll, w:rect.width};");
document.writeln("            }");
document.writeln("");
document.writeln("        };");
document.writeln("");
document.writeln("        // PhotoSwipe opened from URL");
document.writeln("        if(fromURL) {");
document.writeln("            if(options.galleryPIDs) {");
document.writeln("                // parse real index when custom PIDs are used ");
document.writeln("                for(var j = 0; j < items.length; j++) {");
document.writeln("                    if(items[j].pid == index) {");
document.writeln("                        options.index = j;");
document.writeln("                        break;");
document.writeln("                    }");
document.writeln("                }");
document.writeln("            } else {");
document.writeln("                // in URL indexes start from 1");
document.writeln("                options.index = parseInt(index, 10) - 1;");
document.writeln("            }");
document.writeln("        } else {");
document.writeln("            options.index = parseInt(index, 10);");
document.writeln("        }");
document.writeln("");
document.writeln("        // exit if index not found");
document.writeln("        if( isNaN(options.index) ) {");
document.writeln("            return;");
document.writeln("        }");
document.writeln("");
document.writeln("        if(disableAnimation) {");
document.writeln("            options.showAnimationDuration = 0;");
document.writeln("        }");
document.writeln("");
document.writeln("        // Pass data to PhotoSwipe and initialize it");
document.writeln("        gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);");
document.writeln("        gallery.init();");
document.writeln("    };");
document.writeln("");
document.writeln("    // loop through all gallery elements and bind events");
document.writeln("    var galleryElements = document.querySelectorAll( gallerySelector );");
document.writeln("");
document.writeln("    for(var i = 0, l = galleryElements.length; i < l; i++) {");
document.writeln("        galleryElements[i].setAttribute(\'data-pswp-uid\', i+1);");
document.writeln("        galleryElements[i].onclick = onThumbnailsClick;");
document.writeln("    }");
document.writeln("");
document.writeln("    // Parse URL and open gallery if it contains #&pid=3&gid=1");
document.writeln("    var hashData = photoswipeParseHash();");
document.writeln("    if(hashData.pid && hashData.gid) {");
document.writeln("        openPhotoSwipe( hashData.pid ,  galleryElements[ hashData.gid - 1 ], true, true );");
document.writeln("    }");
document.writeln("	};");
document.writeln("");
document.writeln("	// execute above function");
document.writeln("	initPhotoSwipeFromDOM(\'.my-gallery\');");
document.writeln("");
document.writeln("	");
document.writeln("	$(\'.my-gallery>figure>div\').each(function(){");
document.writeln("		$(this).height($(this).width());");
document.writeln("	});");
document.writeln("	function more(obj,id) {");
document.writeln(" 		if ($(\'#txt\'+id).is(\':hidden\')) {");
document.writeln(" 			$(\'#p\'+id).hide();");
document.writeln(" 	 		$(\'#txt\'+id).show();");
document.writeln(" 	 		obj.innerHTML=\'����\';");
document.writeln(" 		} else {");
document.writeln(" 			$(\'#p\'+id).show();");
document.writeln(" 	 		$(\'#txt\'+id).hide();");
document.writeln(" 	 		obj.innerHTML=\'ȫ��\';");
document.writeln(" 		}");
document.writeln(" 	}");
document.writeln("</script>");
document.writeln("");